### ISSUE TITLE
Update the base version of Sirius Web used for the example

### ISSUE THREAD

**Issue by pcdavid** [ObeoNetwork/Sirius-Web-Tutorial#12]

**Comment by pcdavid** [comment]
Target: 2023.10.0 + patches for H2 support.

**Comment by pcdavid** [comment]
https://github.com/eclipse-sirius/sirius-web/tree/ari/enh/h2

**Comment by AxelRICHARD** [comment]
2023.8.4-econ based on H2 (specific version with no official release)
