### ISSUE TITLE
L'exemple avec Man/Woman et les images associées peut être mal interprété

### ISSUE THREAD

**Issue by pcdavid** [ObeoNetwork/Sirius-Web-Tutorial#9]
Contexte: https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php: 

> Using welcoming and inclusive language;

**Comment by pcdavid** [comment]
Possible idea: distinguish parents & grand-parents to switch between "child", "adult", "elderly" images.
The means the section does not require changing the domain definition (not sure if it's a net positive or negative: it becomes shorter, but show less of the system's features and workings).

**Comment by AxelRICHARD** [comment]
Another possibility: something not related to the family links, like StarWars Fan/StarTrek Fan or EmpireMember/RepublicMember or C-3PO Fan/R2-D2 Fan or Lennon Fan / McCartney Fan...

**Comment by pcdavid** [comment]
I guess we can close this one with #17 merged?
